# Notebook 25 – Power BI Data Preparation

## Objective

This notebook prepares explainability datasets for Power BI.

It converts the wide-format transaction explainability dataset into a normalized long-format dataset suitable for interactive visualizations.

### Input

transaction_explainability.csv

### Output

feature_contributions_long.csv

## Imports

In [9]:
import os
import pandas as pd

## Paths

In [10]:
INPUT_FILE = "../powerbi_assets/explainability/transaction_explainability.csv"

OUTPUT_FILE = "../powerbi_assets/explainability/feature_contributions_long.csv"

## Load Dataset

In [11]:
df = pd.read_csv(INPUT_FILE)

print(df.shape)

display(df.head())

(56746, 16)

,Transaction_ID,Actual,Prediction,Fraud_Probability,Risk_Level,Recommendation,Top_Feature_1,Contribution_1,Top_Feature_2,Contribution_2,Top_Feature_3,Contribution_3,Top_Feature_4,Contribution_4,Top_Feature_5,Contribution_5
0,TRX-000001,0,0,0.0,Low,Approve Transaction,V12,-0.082708,V11,-0.076246,V3,-0.065172,V14,-0.062817,V10,-0.040793
1,TRX-000002,0,0,0.0,Low,Approve Transaction,V11,-0.092674,V14,-0.075934,V12,-0.071266,V10,-0.046229,V4,-0.045034
2,TRX-000003,0,0,0.0,Low,Approve Transaction,V3,-0.102495,V10,-0.091733,V12,-0.080081,V14,-0.048524,V4,0.037371
3,TRX-000004,0,0,0.0,Low,Approve Transaction,V12,-0.091367,V14,-0.076734,V3,-0.075118,V10,-0.056169,V17,-0.033981
4,TRX-000005,0,0,0.0,Low,Approve Transaction,V12,-0.121237,V10,-0.053267,V1,-0.037587,V4,-0.035067,V17,-0.031866

## Convert Wide → Long

In [12]:
records = []

for _, row in df.iterrows():

    for rank in range(1, 6):

        records.append({

            "Transaction_ID": row["Transaction_ID"],

            "Prediction": row["Prediction"],

            "Fraud_Probability": row["Fraud_Probability"],

            "Risk_Level": row["Risk_Level"],

            "Recommendation": row["Recommendation"],

            "Rank": rank,

            "Feature": row[f"Top_Feature_{rank}"],

            "Contribution": row[f"Contribution_{rank}"]

        })

feature_long = pd.DataFrame(records)

## Preview

In [13]:
display(feature_long.head(20))

,Transaction_ID,Prediction,Fraud_Probability,Risk_Level,Recommendation,Rank,Feature,Contribution
0,TRX-000001,0,0.0,Low,Approve Transaction,1,V12,-0.082708
1,TRX-000001,0,0.0,Low,Approve Transaction,2,V11,-0.076246
2,TRX-000001,0,0.0,Low,Approve Transaction,3,V3,-0.065172
3,TRX-000001,0,0.0,Low,Approve Transaction,4,V14,-0.062817
4,TRX-000001,0,0.0,Low,Approve Transaction,5,V10,-0.040793
5,TRX-000002,0,0.0,Low,Approve Transaction,1,V11,-0.092674
6,TRX-000002,0,0.0,Low,Approve Transaction,2,V14,-0.075934
7,TRX-000002,0,0.0,Low,Approve Transaction,3,V12,-0.071266
8,TRX-000002,0,0.0,Low,Approve Transaction,4,V10,-0.046229
9,TRX-000002,0,0.0,Low,Approve Transaction,5,V4,-0.045034
10,TRX-000003,0,0.0,Low,Approve Transaction,1,V3,-0.102495
11,TRX-000003,0,0.0,Low,Approve Transaction,2,V10,-0.091733
12,TRX-000003,0,0.0,Low,Approve Transaction,3,V12,-0.080081
13,TRX-000003,0,0.0,Low,Approve Transaction,4,V14,-0.048524
14,TRX-000003,0,0.0,Low,Approve Transaction,5,V4,0.037371
15,TRX-000004,0,0.0,Low,Approve Transaction,1,V12,-0.091367
16,TRX-000004,0,0.0,Low,Approve Transaction,2,V14,-0.076734
17,TRX-000004,0,0.0,Low,Approve Transaction,3,V3,-0.075118
18,TRX-000004,0,0.0,Low,Approve Transaction,4,V10,-0.056169
19,TRX-000004,0,0.0,Low,Approve Transaction,5,V17,-0.033981

## Sort

In [14]:
feature_long = (

    feature_long

    .sort_values(

        ["Transaction_ID", "Rank"]

    )

    .reset_index(drop=True)

)

## Export

In [15]:
feature_long.to_csv(

    OUTPUT_FILE,

    index=False

)

print("Power BI Dataset Created Successfully")

print()

print(OUTPUT_FILE)

Power BI Dataset Created Successfully

../powerbi_assets/explainability/feature_contributions_long.csv

## Verification

In [16]:
print("=" * 70)

print("Verification")

print("=" * 70)

print()

print(feature_long.shape)

print()

display(feature_long.head())

print()

display(feature_long.tail())

======================================================================
Verification
======================================================================

(283730, 8)

,Transaction_ID,Prediction,Fraud_Probability,Risk_Level,Recommendation,Rank,Feature,Contribution
0,TRX-000001,0,0.0,Low,Approve Transaction,1,V12,-0.082708
1,TRX-000001,0,0.0,Low,Approve Transaction,2,V11,-0.076246
2,TRX-000001,0,0.0,Low,Approve Transaction,3,V3,-0.065172
3,TRX-000001,0,0.0,Low,Approve Transaction,4,V14,-0.062817
4,TRX-000001,0,0.0,Low,Approve Transaction,5,V10,-0.040793

,Transaction_ID,Prediction,Fraud_Probability,Risk_Level,Recommendation,Rank,Feature,Contribution
283725,TRX-056746,0,0.0,Low,Approve Transaction,1,V14,-0.106899
283726,TRX-056746,0,0.0,Low,Approve Transaction,2,V3,-0.089996
283727,TRX-056746,0,0.0,Low,Approve Transaction,3,V10,-0.043445
283728,TRX-056746,0,0.0,Low,Approve Transaction,4,V17,-0.038643
283729,TRX-056746,0,0.0,Low,Approve Transaction,5,V4,-0.027367